import { useState, useEffect } from "react";

// ── Palette & helpers ──────────────────────────────────────────────────────
const C = {
  navy:   "#05051A",
  purple: "#534AB7",
  purpleL:"#7B74D4",
  teal:   "#1D9E75",
  tealL:  "#2DC994",
  amber:  "#FFB830",
  red:    "#E03B3B",
  card:   "#0E0C2A",
  border: "#2A2660",
  muted:  "#8888BB",
  offwh:  "#E8E6FF",
  white:  "#FFFFFF",
  light:  "#F5F4FF",
};

const fmt = (n) => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
const today = () => new Date().toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric"});
const addDays = (d,n) => { const r=new Date(d); r.setDate(r.getDate()+n); return r.toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric"}); };

const PLANS = [
  { id:"starter", name:"Starter",  price:29,  docs:50,  formats:["Markdown"],              color:C.teal,   badge:"Popular" },
  { id:"pro",     name:"Pro",      price:79,  docs:500, formats:["Markdown","HTML","PDF"],  color:C.purple, badge:"Best Value" },
  { id:"team",    name:"Team",     price:199, docs:9999,formats:["Markdown","HTML","PDF","GitHub Actions"], color:C.amber, badge:"Enterprise" },
];

// ── Fake doc generator ──────────────────────────────────────────────────────
const SAMPLE_DOC = `# DocGen — API Reference

> Generated by DocGen AI using IBM Bob  
> Date: ${today()}

---

## Module \`data_utils\`

**File:** \`data_utils.py\`

Provides core data ingestion, normalisation, and statistical utilities.

---

### \`normalise\`

\`\`\`python
def normalise(values: List[float], scale: float = 1.0) -> List[float]
\`\`\`

Normalises a list of float values to a [0, scale] range.

**Args:**
- \`values\` *(List[float])*: Input numeric values.
- \`scale\` *(float)*: Upper bound of the output range. Defaults to 1.0.

**Returns:** Normalised list of floats.

**Example:**
\`\`\`python
>>> normalise([0, 50, 100], scale=1.0)
[0.0, 0.5, 1.0]
\`\`\`

---

### \`compute_stats\`

\`\`\`python
def compute_stats(data: List[float]) -> dict
\`\`\`

Computes descriptive statistics for a numeric dataset.

**Args:**
- \`data\` *(List[float])*: Input data.

**Returns:** Dict with keys \`count\`, \`mean\`, \`std\`, \`min\`, \`max\`.

---

## Class \`DataProcessor\`

Handles raw data ingestion and transformation pipelines.

**Methods:**
- \`load(records)\` — Load a list of records, enforcing max_records limit.
- \`filter(key, value)\` — Filter records by key-value match.
- \`summarise()\` — Return a summary dict with name and record count.
`;

// ── Invoice generator ───────────────────────────────────────────────────────
function buildInvoice(plan, customer, invoiceNum) {
  const now = new Date();
  const due  = addDays(now, 7);
  return {
    number: invoiceNum,
    date: today(),
    due,
    customer,
    plan,
    subtotal: plan.price,
    tax: +(plan.price * 0.1).toFixed(2),
    total: +(plan.price * 1.1).toFixed(2),
    status: "PAID",
  };
}

// ── Shared UI atoms ─────────────────────────────────────────────────────────
const Pill = ({ children, color=C.purple }) => (
  <span style={{
    background: color + "22", color, border: `1px solid ${color}44`,
    borderRadius: 20, padding: "2px 10px", fontSize: 11, fontWeight: 700,
    letterSpacing: "0.05em", textTransform: "uppercase",
  }}>{children}</span>
);

const Btn = ({ children, onClick, variant="primary", disabled, style={} }) => {
  const base = {
    padding: "11px 28px", borderRadius: 8, border: "none", cursor: disabled?"not-allowed":"pointer",
    fontWeight: 700, fontSize: 14, letterSpacing: "0.03em", transition: "all 0.18s",
    opacity: disabled ? 0.5 : 1, fontFamily: "inherit", ...style,
  };
  const vars = {
    primary:   { background: C.purple,  color: C.white },
    teal:      { background: C.teal,    color: C.white },
    ghost:     { background: "transparent", color: C.offwh, border: `1px solid ${C.border}` },
    danger:    { background: C.red,     color: C.white },
  };
  return <button style={{...base, ...vars[variant]}} onClick={disabled?undefined:onClick}>{children}</button>;
};

const Card = ({ children, style={} }) => (
  <div style={{
    background: C.card, border: `1px solid ${C.border}`, borderRadius: 14,
    padding: "24px", ...style,
  }}>{children}</div>
);

// ── STEP 1: Hero Landing ──────────────────────────────────────────────────
function HeroStep({ onStart }) {
  return (
    <div style={{ textAlign:"center", padding:"40px 0 20px" }}>
      <div style={{
        display:"inline-block", background: C.teal+"22", border:`1px solid ${C.teal}44`,
        borderRadius:20, padding:"4px 16px", fontSize:11, fontWeight:700,
        color:C.teal, letterSpacing:"0.08em", marginBottom:20,
      }}>✦ IBM BOB HACKATHON 2026</div>

      <h1 style={{
        fontSize:"clamp(2.8rem,6vw,4.2rem)", fontWeight:900, lineHeight:1.05,
        color:C.white, margin:"0 0 14px", fontFamily:"'Georgia', serif",
        letterSpacing:"-0.02em",
      }}>
        DocGen <span style={{color:C.purple}}>Pro</span>
      </h1>
      <p style={{ fontSize:18, color:C.muted, maxWidth:520, margin:"0 auto 32px", lineHeight:1.6 }}>
        AI-powered documentation generator with <strong style={{color:C.white}}>3-day free trial</strong>.
        Automatically generate docs, manage subscriptions, and receive invoices.
      </p>

      {/* Feature strip */}
      <div style={{
        display:"flex", flexWrap:"wrap", gap:12, justifyContent:"center", marginBottom:36,
      }}>
        {["📄 AI Doc Generation","🧾 Auto Invoicing","💳 Subscription Billing","🔔 Team Notifications","⚡ 3-Day Free Trial"].map(f => (
          <span key={f} style={{
            background:C.card, border:`1px solid ${C.border}`, borderRadius:20,
            padding:"6px 16px", fontSize:13, color:C.offwh,
          }}>{f}</span>
        ))}
      </div>

      {/* Stats row */}
      <div style={{
        display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:16,
        maxWidth:480, margin:"0 auto 36px",
      }}>
        {[["5,621","Hackathon Users"],["8","Modules Parsed"],["100%","Uptime SLA"]].map(([v,l]) => (
          <div key={l} style={{
            background:C.card, border:`1px solid ${C.border}`, borderRadius:12, padding:"16px 8px",
          }}>
            <div style={{fontSize:26,fontWeight:800,color:C.white}}>{v}</div>
            <div style={{fontSize:11,color:C.muted,marginTop:3}}>{l}</div>
          </div>
        ))}
      </div>

      <Btn onClick={onStart} variant="teal" style={{fontSize:16, padding:"14px 40px"}}>
        🚀 Start Free Trial
      </Btn>
      <p style={{fontSize:12,color:C.muted,marginTop:12}}>No credit card required for 3-day trial</p>
    </div>
  );
}

// ── STEP 2: Plan Selector ──────────────────────────────────────────────────
function PlanStep({ onSelect }) {
  const [hovered, setHovered] = useState(null);
  return (
    <div>
      <h2 style={{color:C.white,textAlign:"center",fontSize:24,fontWeight:800,marginBottom:6}}>
        Choose Your Plan
      </h2>
      <p style={{color:C.muted,textAlign:"center",marginBottom:28,fontSize:14}}>
        All plans start with a <strong style={{color:C.teal}}>3-day free trial</strong>. Cancel anytime.
      </p>

      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:16}}>
        {PLANS.map(plan => (
          <div key={plan.id}
            onMouseEnter={()=>setHovered(plan.id)}
            onMouseLeave={()=>setHovered(null)}
            onClick={()=>onSelect(plan)}
            style={{
              background: hovered===plan.id ? plan.color+"18" : C.card,
              border: `2px solid ${hovered===plan.id ? plan.color : C.border}`,
              borderRadius:16, padding:24, cursor:"pointer",
              transition:"all 0.2s", position:"relative", overflow:"hidden",
            }}>
            {/* Top badge */}
            <div style={{position:"absolute",top:14,right:14}}>
              <Pill color={plan.color}>{plan.badge}</Pill>
            </div>

            <div style={{
              width:44,height:44,borderRadius:10,background:plan.color+"22",
              display:"flex",alignItems:"center",justifyContent:"center",
              fontSize:22,marginBottom:16,
            }}>
              {plan.id==="starter"?"📄":plan.id==="pro"?"⚡":"🏢"}
            </div>

            <div style={{fontSize:22,fontWeight:800,color:C.white,marginBottom:4}}>{plan.name}</div>
            <div style={{marginBottom:16}}>
              <span style={{fontSize:36,fontWeight:900,color:plan.color}}>${plan.price}</span>
              <span style={{color:C.muted,fontSize:14}}>/month</span>
            </div>

            <div style={{borderTop:`1px solid ${C.border}`,paddingTop:14,marginBottom:16}}>
              {[
                `${plan.docs===9999?"Unlimited":plan.docs} docs/month`,
                ...plan.formats.map(f=>`${f} output`),
                "IBM Bob AI engine",
                "Auto invoicing",
                plan.id!=="starter"?"Team Slack alerts":null,
              ].filter(Boolean).map(f=>(
                <div key={f} style={{fontSize:13,color:C.offwh,marginBottom:6,display:"flex",alignItems:"center",gap:8}}>
                  <span style={{color:C.teal}}>✓</span>{f}
                </div>
              ))}
            </div>

            <Btn variant={hovered===plan.id?"teal":"ghost"} style={{width:"100%",justifyContent:"center",display:"block"}}>
              Start Free Trial →
            </Btn>
          </div>
        ))}
      </div>

      <p style={{textAlign:"center",color:C.muted,fontSize:12,marginTop:20}}>
        Trial ends {addDays(new Date(),3)} · Billing starts automatically after trial
      </p>
    </div>
  );
}

// ── STEP 3: Customer Details ───────────────────────────────────────────────
function CustomerStep({ plan, onSubmit }) {
  const [form, setForm] = useState({
    name:"", email:"", company:"", card:"4242 4242 4242 4242", expiry:"12/27", cvv:"123"
  });
  const set = (k,v) => setForm(f=>({...f,[k]:v}));
  const valid = form.name && form.email && form.company;

  const inp = (label, key, placeholder, half=false) => (
    <div style={{flex:half?"1 1 45%":"1 1 100%",minWidth:0}}>
      <label style={{fontSize:12,color:C.muted,display:"block",marginBottom:5,fontWeight:600}}>{label}</label>
      <input
        value={form[key]}
        onChange={e=>set(key,e.target.value)}
        placeholder={placeholder}
        style={{
          width:"100%", boxSizing:"border-box",
          background:"#0A0820", border:`1px solid ${C.border}`,
          borderRadius:8, padding:"10px 14px", color:C.white,
          fontSize:14, outline:"none", fontFamily:"inherit",
        }}
      />
    </div>
  );

  return (
    <div style={{maxWidth:520,margin:"0 auto"}}>
      <div style={{marginBottom:20,display:"flex",alignItems:"center",gap:10}}>
        <div style={{
          background:plan.color+"22",border:`1px solid ${plan.color}44`,
          borderRadius:10,padding:"8px 16px",
        }}>
          <span style={{color:plan.color,fontWeight:700}}>{plan.name} Plan</span>
          <span style={{color:C.muted,fontSize:13}}> — ${plan.price}/mo after trial</span>
        </div>
        <Pill color={C.teal}>3-Day Free Trial</Pill>
      </div>

      <Card>
        <h3 style={{color:C.white,marginBottom:18,fontSize:16,fontWeight:700}}>Your Details</h3>
        <div style={{display:"flex",flexWrap:"wrap",gap:12,marginBottom:20}}>
          {inp("Full Name","name","Newbon Kiroso")}
          {inp("Email","email","you@company.com")}
          {inp("Company","company","Acme Corp")}
        </div>

        <h3 style={{color:C.white,marginBottom:14,fontSize:16,fontWeight:700}}>
          💳 Payment Method <span style={{color:C.muted,fontWeight:400,fontSize:12}}>(charged after trial)</span>
        </h3>
        <div style={{display:"flex",flexWrap:"wrap",gap:12,marginBottom:8}}>
          {inp("Card Number","card","4242 4242 4242 4242")}
          {inp("Expiry","expiry","MM/YY",true)}
          {inp("CVV","cvv","123",true)}
        </div>
        <p style={{fontSize:11,color:C.muted,marginBottom:20}}>
          🔒 Secured with Stripe · Trial ends {addDays(new Date(),3)} · Cancel anytime before billing
        </p>

        <Btn onClick={()=>onSubmit(form)} variant="teal" disabled={!valid}
          style={{width:"100%",justifyContent:"center",display:"block",fontSize:15}}>
          Activate 3-Day Free Trial →
        </Btn>
      </Card>
    </div>
  );
}

// ── STEP 4: Dashboard ──────────────────────────────────────────────────────
function Dashboard({ plan, customer, invoice }) {
  const [tab, setTab] = useState("docs");
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [docFormat, setDocFormat] = useState("markdown");
  const [notification, setNotification] = useState(null);

  const trialEnd = addDays(new Date(), 3);
  const daysLeft = 3;

  const runGenerate = () => {
    setGenerating(true);
    setGenerated(false);
    setTimeout(()=>{
      setGenerating(false);
      setGenerated(true);
      setNotification("✅ Documentation generated + Invoice #" + invoice.number + " issued!");
      setTimeout(()=>setNotification(null),4000);
    }, 2200);
  };

  const tabStyle = (id) => ({
    padding:"8px 20px", borderRadius:8, border:"none", cursor:"pointer",
    background: tab===id ? C.purple : "transparent",
    color: tab===id ? C.white : C.muted,
    fontWeight: tab===id ? 700 : 400,
    fontSize:13, fontFamily:"inherit", transition:"all 0.15s",
  });

  return (
    <div>
      {/* Notification toast */}
      {notification && (
        <div style={{
          position:"fixed",top:20,right:20,
          background:C.teal,color:C.white,padding:"12px 20px",
          borderRadius:10,fontWeight:700,fontSize:14,zIndex:999,
          boxShadow:"0 4px 20px rgba(0,0,0,0.4)",
        }}>{notification}</div>
      )}

      {/* Header */}
      <div style={{
        display:"flex",alignItems:"center",justifyContent:"space-between",
        flexWrap:"wrap",gap:12,marginBottom:24,
      }}>
        <div>
          <h2 style={{color:C.white,margin:0,fontSize:20,fontWeight:800}}>
            Welcome, {customer.name.split(" ")[0]} 👋
          </h2>
          <p style={{color:C.muted,margin:"4px 0 0",fontSize:13}}>{customer.email} · {customer.company}</p>
        </div>
        <div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}>
          <div style={{
            background:"#0A2018",border:`1px solid ${C.teal}44`,borderRadius:20,
            padding:"6px 14px",fontSize:12,color:C.teal,fontWeight:700,
          }}>🟢 Free Trial · {daysLeft} days left · Ends {trialEnd}</div>
          <Pill color={plan.color}>{plan.name} Plan</Pill>
        </div>
      </div>

      {/* Stats */}
      <div style={{
        display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",
        gap:12,marginBottom:24,
      }}>
        {[
          ["Docs Generated","1",C.teal],
          ["Plan","Pro",C.purple],
          ["Next Invoice",`$${invoice.total}`,C.amber],
          ["Trial Status","Active",C.teal],
        ].map(([l,v,c])=>(
          <div key={l} style={{
            background:C.card,border:`1px solid ${C.border}`,borderRadius:12,
            padding:"16px",
          }}>
            <div style={{fontSize:11,color:C.muted,marginBottom:4,textTransform:"uppercase",letterSpacing:"0.06em"}}>{l}</div>
            <div style={{fontSize:22,fontWeight:800,color:c}}>{v}</div>
          </div>
        ))}
      </div>

      {/* Tabs */}
      <div style={{
        display:"flex",gap:4,marginBottom:20,background:C.card,
        padding:4,borderRadius:10,width:"fit-content",
        border:`1px solid ${C.border}`,
      }}>
        {[["docs","📄 Generate Docs"],["invoice","🧾 Invoice"],["subscription","💳 Subscription"]].map(([id,label])=>(
          <button key={id} style={tabStyle(id)} onClick={()=>setTab(id)}>{label}</button>
        ))}
      </div>

      {/* Tab: Generate Docs */}
      {tab==="docs" && (
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
          {/* Left: controls */}
          <Card>
            <h3 style={{color:C.white,margin:"0 0 16px",fontSize:15,fontWeight:700}}>Generate Documentation</h3>

            <label style={{fontSize:12,color:C.muted,display:"block",marginBottom:6,fontWeight:600}}>
              Repository Path
            </label>
            <input defaultValue="./my_project" style={{
              width:"100%",boxSizing:"border-box",background:"#0A0820",
              border:`1px solid ${C.border}`,borderRadius:8,padding:"10px 14px",
              color:C.white,fontSize:13,fontFamily:"monospace",marginBottom:14,
            }}/>

            <label style={{fontSize:12,color:C.muted,display:"block",marginBottom:8,fontWeight:600}}>
              Output Format
            </label>
            <div style={{display:"flex",gap:8,marginBottom:18,flexWrap:"wrap"}}>
              {plan.formats.map(f=>(
                <button key={f} onClick={()=>setDocFormat(f.toLowerCase())}
                  style={{
                    padding:"6px 14px",borderRadius:20,border:`1px solid`,
                    borderColor: docFormat===f.toLowerCase() ? C.purple : C.border,
                    background: docFormat===f.toLowerCase() ? C.purple+"33" : "transparent",
                    color: docFormat===f.toLowerCase() ? C.offwh : C.muted,
                    fontSize:12,cursor:"pointer",fontFamily:"inherit",transition:"all 0.15s",
                  }}>{f}</button>
              ))}
            </div>

            <Btn onClick={runGenerate} variant="teal"
              style={{width:"100%",display:"block",fontSize:14}} disabled={generating}>
              {generating ? "⏳ Generating with IBM Bob..." : "▶ Generate Documentation"}
            </Btn>

            {generating && (
              <div style={{marginTop:16}}>
                {["Parsing Python source...","Sending to IBM Bob...","Compiling output..."].map((s,i)=>(
                  <div key={s} style={{
                    fontSize:12,color:C.muted,padding:"4px 0",
                    display:"flex",alignItems:"center",gap:8,
                    animation:`fadeIn 0.3s ${i*0.6}s both`,
                  }}>
                    <span style={{color:C.teal}}>›</span>{s}
                  </div>
                ))}
              </div>
            )}

            {generated && !generating && (
              <div style={{
                marginTop:14,background:"#0A2018",border:`1px solid ${C.teal}44`,
                borderRadius:8,padding:12,
              }}>
                <div style={{fontSize:12,color:C.teal,fontWeight:700,marginBottom:6}}>
                  ✓ Done! Docs saved to ./output
                </div>
                {[`output/my_project_docs.md`,
                  ...(plan.formats.includes("HTML")?[`output/my_project_docs.html`]:[]),
                  ...(plan.formats.includes("PDF")?[`output/my_project_docs.pdf`]:[]),
                ].map(f=>(
                  <div key={f} style={{fontSize:11,color:C.muted,marginBottom:2}}>📄 {f}</div>
                ))}
              </div>
            )}
          </Card>

          {/* Right: doc preview */}
          <Card style={{overflow:"hidden"}}>
            <div style={{
              display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:12,
            }}>
              <h3 style={{color:C.white,margin:0,fontSize:15,fontWeight:700}}>Preview</h3>
              {generated && <Pill color={C.teal}>Generated</Pill>}
            </div>
            <div style={{
              background:"#06060F",borderRadius:8,padding:14,
              fontFamily:"monospace",fontSize:11,color:"#A0A0C8",
              height:320,overflowY:"auto",lineHeight:1.6,whiteSpace:"pre-wrap",
              border:`1px solid ${C.border}`,
            }}>
              {generated
                ? SAMPLE_DOC
                : <span style={{color:C.muted}}>Run generation to preview output here...</span>
              }
            </div>
          </Card>
        </div>
      )}

      {/* Tab: Invoice */}
      {tab==="invoice" && <InvoiceView invoice={invoice} plan={plan} customer={customer}/>}

      {/* Tab: Subscription */}
      {tab==="subscription" && <SubscriptionView plan={plan} customer={customer} invoice={invoice} trialEnd={trialEnd}/>}
    </div>
  );
}

// ── Invoice View ───────────────────────────────────────────────────────────
function InvoiceView({ invoice, plan, customer }) {
  const [printing, setPrinting] = useState(false);
  const handlePrint = () => {
    setPrinting(true);
    setTimeout(()=>setPrinting(false),1200);
    window.print?.();
  };

  return (
    <div style={{maxWidth:640,margin:"0 auto"}}>
      <div style={{
        display:"flex",alignItems:"center",justifyContent:"space-between",
        marginBottom:16,flexWrap:"wrap",gap:10,
      }}>
        <h3 style={{color:C.white,margin:0,fontSize:16,fontWeight:700}}>Invoice</h3>
        <div style={{display:"flex",gap:8}}>
          <Btn variant="ghost" onClick={handlePrint} style={{fontSize:12,padding:"8px 16px"}}>
            🖨 Print / Save PDF
          </Btn>
          <Pill color={C.teal}>{invoice.status}</Pill>
        </div>
      </div>

      {/* Invoice card */}
      <div style={{
        background:C.white,borderRadius:16,padding:"32px 36px",color:"#111",
        fontFamily:"'Georgia', serif",
      }}>
        {/* Header */}
        <div style={{
          display:"flex",justifyContent:"space-between",alignItems:"flex-start",
          borderBottom:"2px solid #534AB7",paddingBottom:20,marginBottom:24,
          flexWrap:"wrap",gap:12,
        }}>
          <div>
            <div style={{fontSize:28,fontWeight:900,color:"#534AB7",letterSpacing:"-0.02em"}}>
              DocGen
            </div>
            <div style={{fontSize:12,color:"#888",marginTop:2}}>
              AI-Powered Documentation Platform
            </div>
            <div style={{fontSize:11,color:"#888",marginTop:1}}>
              IBM Bob Hackathon 2026 · lablab.ai
            </div>
          </div>
          <div style={{textAlign:"right"}}>
            <div style={{fontSize:22,fontWeight:700,color:"#111"}}>INVOICE</div>
            <div style={{fontSize:13,color:"#555",marginTop:4}}>#{invoice.number}</div>
            <div style={{
              display:"inline-block",background:"#1D9E7522",
              border:"1px solid #1D9E75",borderRadius:20,
              padding:"3px 12px",fontSize:11,fontWeight:700,color:"#1D9E75",marginTop:8,
            }}>● PAID</div>
          </div>
        </div>

        {/* Bill to / dates */}
        <div style={{
          display:"grid",gridTemplateColumns:"1fr 1fr",gap:24,marginBottom:24,
        }}>
          <div>
            <div style={{fontSize:10,fontWeight:700,color:"#888",textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>
              Bill To
            </div>
            <div style={{fontWeight:700,fontSize:15}}>{customer.name}</div>
            <div style={{fontSize:13,color:"#555"}}>{customer.company}</div>
            <div style={{fontSize:13,color:"#555"}}>{customer.email}</div>
          </div>
          <div>
            <div style={{fontSize:10,fontWeight:700,color:"#888",textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>
              Details
            </div>
            <div style={{fontSize:13}}><strong>Invoice Date:</strong> {invoice.date}</div>
            <div style={{fontSize:13}}><strong>Due Date:</strong> {invoice.due}</div>
            <div style={{fontSize:13}}><strong>Period:</strong> Monthly subscription</div>
          </div>
        </div>

        {/* Line items */}
        <table style={{width:"100%",borderCollapse:"collapse",marginBottom:20}}>
          <thead>
            <tr style={{background:"#F5F4FF"}}>
              {["Description","Qty","Unit Price","Amount"].map(h=>(
                <th key={h} style={{
                  padding:"8px 12px",textAlign:"left",fontSize:11,
                  fontWeight:700,color:"#534AB7",textTransform:"uppercase",letterSpacing:"0.06em",
                  borderBottom:"1px solid #DDD",
                }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{padding:"12px",fontSize:13,borderBottom:"1px solid #EEE"}}>
                <strong>DocGen {plan.name} Plan</strong><br/>
                <span style={{color:"#888",fontSize:11}}>
                  {plan.docs===9999?"Unlimited":plan.docs} docs/month · {plan.formats.join(", ")} outputs · IBM Bob AI
                </span>
              </td>
              <td style={{padding:"12px",fontSize:13,borderBottom:"1px solid #EEE"}}>1</td>
              <td style={{padding:"12px",fontSize:13,borderBottom:"1px solid #EEE"}}>{fmt(plan.price)}</td>
              <td style={{padding:"12px",fontSize:13,borderBottom:"1px solid #EEE"}}>{fmt(plan.price)}</td>
            </tr>
            <tr>
              <td colSpan={3} style={{padding:"10px 12px",fontSize:13,textAlign:"right",color:"#888"}}>
                3-Day Free Trial Discount
              </td>
              <td style={{padding:"10px 12px",fontSize:13,color:"#1D9E75",fontWeight:700}}>
                -{fmt(plan.price)}
              </td>
            </tr>
          </tbody>
        </table>

        {/* Totals */}
        <div style={{
          display:"flex",flexDirection:"column",alignItems:"flex-end",
          borderTop:"2px solid #EEE",paddingTop:16,gap:6,
        }}>
          {[["Subtotal", fmt(invoice.subtotal)],["Tax (10%)", fmt(invoice.tax)],].map(([l,v])=>(
            <div key={l} style={{display:"flex",gap:80,fontSize:13}}>
              <span style={{color:"#888"}}>{l}</span><span>{v}</span>
            </div>
          ))}
          <div style={{
            display:"flex",gap:80,fontSize:16,fontWeight:800,
            borderTop:"2px solid #534AB7",paddingTop:10,marginTop:4,color:"#534AB7",
          }}>
            <span>Total Due After Trial</span><span>{fmt(invoice.total)}</span>
          </div>
        </div>

        {/* Footer note */}
        <div style={{
          marginTop:24,padding:"12px 16px",background:"#F5F4FF",
          borderRadius:8,borderLeft:"3px solid #534AB7",fontSize:12,color:"#555",
        }}>
          <strong>Free Trial Notice:</strong> Your 3-day trial started today ({invoice.date}).
          You will be charged {fmt(invoice.total)} on {addDays(new Date(),3)}.
          Cancel anytime before then at no charge.
        </div>

        {/* Bottom */}
        <div style={{
          marginTop:20,textAlign:"center",fontSize:11,color:"#AAA",
          borderTop:"1px solid #EEE",paddingTop:16,
        }}>
          DocGen · IBM Bob Hackathon 2026 · support@docgen.ai · lablab.ai
        </div>
      </div>
    </div>
  );
}

// ── Subscription View ──────────────────────────────────────────────────────
function SubscriptionView({ plan, customer, invoice, trialEnd }) {
  const [cancelled, setCancelled] = useState(false);
  return (
    <div style={{maxWidth:540,margin:"0 auto"}}>
      <Card style={{marginBottom:16}}>
        <h3 style={{color:C.white,margin:"0 0 16px",fontSize:15,fontWeight:700}}>
          Subscription Status
        </h3>
        <div style={{
          display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:16,
        }}>
          {[
            ["Plan",`${plan.name} · $${plan.price}/mo`],
            ["Status", cancelled?"Cancelled":"Free Trial Active"],
            ["Trial Ends",trialEnd],
            ["Next Billing",cancelled?"—":trialEnd],
            ["Billing Amount",cancelled?"—":fmt(invoice.total)],
            ["Payment Method","Visa ending 4242"],
          ].map(([l,v])=>(
            <div key={l} style={{
              background:"#08061A",border:`1px solid ${C.border}`,borderRadius:8,padding:"12px",
            }}>
              <div style={{fontSize:11,color:C.muted,marginBottom:3,textTransform:"uppercase",letterSpacing:"0.05em"}}>{l}</div>
              <div style={{fontSize:13,fontWeight:600,color:cancelled&&l==="Status"?C.red:C.white}}>{v}</div>
            </div>
          ))}
        </div>

        {!cancelled ? (
          <div>
            <div style={{
              background:"#0A2018",border:`1px solid ${C.teal}44`,
              borderRadius:8,padding:"12px 16px",marginBottom:16,
              fontSize:13,color:C.teal,
            }}>
              🟢 Trial active — you won't be charged until <strong>{trialEnd}</strong>
            </div>
            <Btn variant="danger" onClick={()=>setCancelled(true)}
              style={{width:"100%",display:"block"}}>
              Cancel Subscription (No Charge During Trial)
            </Btn>
          </div>
        ) : (
          <div style={{
            background:"#200808",border:`1px solid ${C.red}44`,
            borderRadius:8,padding:"12px 16px",textAlign:"center",
          }}>
            <div style={{color:C.red,fontWeight:700,fontSize:14}}>Subscription Cancelled</div>
            <div style={{color:C.muted,fontSize:12,marginTop:4}}>
              No charges applied. Access continues until trial ends.
            </div>
          </div>
        )}
      </Card>

      {/* CRM / Notification log */}
      <Card>
        <h3 style={{color:C.white,margin:"0 0 14px",fontSize:15,fontWeight:700}}>
          🔔 Notification Log
        </h3>
        {[
          { time:"Just now",  icon:"🟢", msg:`Trial activated for ${customer.email}`, tag:"Stripe" },
          { time:"Just now",  icon:"📄", msg:`Invoice #${invoice.number} generated`,  tag:"Billing" },
          { time:"Just now",  icon:"📧", msg:`Welcome email sent to ${customer.email}`,tag:"Email" },
          { time:"Just now",  icon:"💬", msg:`CRM record created — ${customer.company}`, tag:"HubSpot" },
          { time:"In 3 days", icon:"⚠️", msg:`Trial ending reminder scheduled`,        tag:"Scheduler" },
          { time:"In 3 days", icon:"💳", msg:`Charge ${fmt(invoice.total)} on card ••••4242`, tag:"Stripe" },
        ].map((e,i)=>(
          <div key={i} style={{
            display:"flex",alignItems:"flex-start",gap:12,
            padding:"10px 0",borderBottom:i<5?`1px solid ${C.border}`:"none",
          }}>
            <span style={{fontSize:16}}>{e.icon}</span>
            <div style={{flex:1}}>
              <div style={{fontSize:13,color:C.offwh}}>{e.msg}</div>
              <div style={{fontSize:11,color:C.muted,marginTop:2}}>{e.time}</div>
            </div>
            <Pill color={e.tag==="Stripe"?C.purple:e.tag==="Billing"?C.amber:e.tag==="Email"?C.teal:C.muted}>
              {e.tag}
            </Pill>
          </div>
        ))}
      </Card>
    </div>
  );
}

// ── Root App ───────────────────────────────────────────────────────────────
export default function App() {
  const [step, setStep]         = useState("hero");
  const [plan, setPlan]         = useState(null);
  const [customer, setCustomer] = useState(null);
  const [invoice, setInvoice]   = useState(null);

  const steps = ["hero","plan","customer","dashboard"];
  const stepIdx = steps.indexOf(step);

  const handleSelectPlan = (p) => { setPlan(p); setStep("customer"); };
  const handleSubmitCustomer = (form) => {
    setCustomer(form);
    const inv = buildInvoice(plan, form, "INV-2026-001");
    setInvoice(inv);
    setStep("dashboard");
  };

  return (
    <div style={{
      minHeight:"100vh",background:C.navy,fontFamily:"'Trebuchet MS', sans-serif",
      color:C.white,
    }}>
      <style>{`
        @keyframes fadeIn { from{opacity:0;transform:translateY(6px)} to{opacity:1;transform:none} }
        input:focus { border-color: #534AB7 !important; }
        ::-webkit-scrollbar { width:6px; }
        ::-webkit-scrollbar-track { background:#0A0820; }
        ::-webkit-scrollbar-thumb { background:#2A2660; border-radius:3px; }
      `}</style>

      {/* Top nav */}
      <div style={{
        background:"#08071A", borderBottom:`1px solid ${C.border}`,
        padding:"14px 28px", display:"flex", alignItems:"center",
        justifyContent:"space-between", position:"sticky", top:0, zIndex:100,
      }}>
        <div style={{display:"flex",alignItems:"center",gap:10}}>
          <span style={{fontSize:20,fontWeight:900,color:C.white,letterSpacing:"-0.02em"}}>
            Doc<span style={{color:C.purple}}>Gen</span>
          </span>
          <Pill color={C.teal}>Free Trial</Pill>
        </div>
        {step!=="hero" && (
          <div style={{display:"flex",gap:6}}>
            {["Plan","Details","Dashboard"].map((s,i)=>(
              <div key={s} style={{
                display:"flex",alignItems:"center",gap:6,fontSize:12,
                color: stepIdx>i+1 ? C.teal : stepIdx===i+1 ? C.white : C.muted,
              }}>
                <span style={{
                  width:20,height:20,borderRadius:"50%",display:"inline-flex",
                  alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:700,
                  background: stepIdx>i+1 ? C.teal : stepIdx===i+1 ? C.purple : C.border,
                  color:C.white,
                }}>{stepIdx>i+1?"✓":i+2}</span>
                {s}
                {i<2 && <span style={{color:C.border,margin:"0 2px"}}>›</span>}
              </div>
            ))}
          </div>
        )}
        <div style={{fontSize:12,color:C.muted}}>IBM Bob Hackathon 2026</div>
      </div>

      {/* Main content */}
      <div style={{maxWidth:900,margin:"0 auto",padding:"32px 20px 60px"}}>
        {step==="hero"     && <HeroStep onStart={()=>setStep("plan")}/>}
        {step==="plan"     && <PlanStep onSelect={handleSelectPlan}/>}
        {step==="customer" && <CustomerStep plan={plan} onSubmit={handleSubmitCustomer}/>}
        {step==="dashboard"&& <Dashboard plan={plan} customer={customer} invoice={invoice}/>}
      </div>
    </div>
  );
}
