"""
exporter.py — Converts generated docs into Markdown, HTML, and PDF formats.
"""

import os
from typing import Dict, Any


# ─── Markdown ────────────────────────────────────────────────────────────────

def _fn_to_markdown(fn: Dict) -> str:
    prefix = "async " if fn.get("is_async") else ""
    args_str = ", ".join(
        a["name"] + (f": {a['annotation']}" if a.get("annotation") else "") +
        (f" = {a['default']}" if a.get("default") else "")
        for a in fn.get("args", [])
    )
    sig = f"{prefix}{fn['name']}({args_str})"
    if fn.get("return_annotation"):
        sig += f" → {fn['return_annotation']}"

    decorators = "".join(f"@{d}  \n" for d in fn.get("decorators", []))
    doc = fn.get("docstring", "").strip()

    return f"### `{fn['name']}`\n\n{decorators}```python\n{sig}\n```\n\n{doc}\n\n---\n"


def _cls_to_markdown(cls: Dict) -> str:
    bases = f"({', '.join(cls['bases'])})" if cls.get("bases") else ""
    doc = cls.get("docstring", "").strip()
    methods_md = "\n".join(_fn_to_markdown(m) for m in cls.get("methods", []) if not m["name"].startswith("_"))

    return f"## Class `{cls['name']}{bases}`\n\n{doc}\n\n### Methods\n\n{methods_md}\n"


def export_markdown(docs: Dict[str, Any], output_dir: str, project_name: str) -> str:
    lines = [f"# {project_name} — API Reference\n\n"]
    lines.append(f"> Generated by DocGen using IBM Bob AI\n\n")
    lines.append("## Table of Contents\n\n")

    for mod in docs["modules"]:
        lines.append(f"- [{mod['name']}](#{mod['name'].lower()})\n")

    lines.append("\n---\n\n")

    for mod in docs["modules"]:
        lines.append(f"# Module `{mod['name']}`\n\n")
        lines.append(f"**File:** `{os.path.basename(mod['file'])}`\n\n")
        lines.append(f"{mod.get('docstring', '').strip()}\n\n")

        if mod.get("functions"):
            lines.append("## Functions\n\n")
            for fn in mod["functions"]:
                lines.append(_fn_to_markdown(fn))

        for cls in mod.get("classes", []):
            lines.append(_cls_to_markdown(cls))

        lines.append("\n---\n\n")

    content = "".join(lines)
    path = os.path.join(output_dir, f"{project_name.lower().replace(' ', '_')}_docs.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path


# ─── HTML ────────────────────────────────────────────────────────────────────

def _fn_to_html(fn: Dict) -> str:
    prefix = "async " if fn.get("is_async") else ""
    args_str = ", ".join(
        a["name"] + (f": {a['annotation']}" if a.get("annotation") else "") +
        (f" = {a['default']}" if a.get("default") else "")
        for a in fn.get("args", [])
    )
    sig = f"{prefix}{fn['name']}({args_str})"
    if fn.get("return_annotation"):
        sig += f" → {fn['return_annotation']}"
    doc = fn.get("docstring", "").strip().replace("\n", "<br>")
    return f"""
    <div class="fn-card">
      <h3><code>{fn['name']}</code></h3>
      <pre class="sig">{sig}</pre>
      <p class="doc">{doc}</p>
    </div>"""


def _cls_to_html(cls: Dict) -> str:
    bases = f"({', '.join(cls['bases'])})" if cls.get("bases") else ""
    doc = cls.get("docstring", "").strip().replace("\n", "<br>")
    methods_html = "".join(_fn_to_html(m) for m in cls.get("methods", []) if not m["name"].startswith("_"))
    return f"""
  <section class="class-section">
    <h2>Class <code>{cls['name']}{bases}</code></h2>
    <p class="doc">{doc}</p>
    <h3>Methods</h3>
    {methods_html}
  </section>"""


def export_html(docs: Dict[str, Any], output_dir: str, project_name: str) -> str:
    nav_items = "".join(
        f'<li><a href="#{m["name"]}">{m["name"]}</a></li>'
        for m in docs["modules"]
    )

    module_sections = ""
    for mod in docs["modules"]:
        fns_html = "".join(_fn_to_html(f) for f in mod.get("functions", []))
        cls_html = "".join(_cls_to_html(c) for c in mod.get("classes", []))
        module_sections += f"""
  <section id="{mod['name']}" class="module-section">
    <h1>Module <code>{mod['name']}</code></h1>
    <p class="file-path">{os.path.basename(mod['file'])}</p>
    <p class="doc">{mod.get('docstring', '').strip().replace(chr(10), '<br>')}</p>
    {f'<h2>Functions</h2>{fns_html}' if fns_html else ''}
    {cls_html}
  </section>
  <hr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{project_name} — Docs</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 15px; line-height: 1.7; color: #1a1a1a; background: #fafafa; }}
    nav {{ position: sticky; top: 0; background: #1c1c2e; color: #fff; padding: 12px 24px; display: flex; align-items: center; gap: 24px; z-index: 100; }}
    nav h1 {{ font-size: 16px; font-weight: 600; color: #a78bfa; }}
    nav ul {{ list-style: none; display: flex; gap: 12px; flex-wrap: wrap; }}
    nav a {{ color: #c4b5fd; text-decoration: none; font-size: 13px; }}
    nav a:hover {{ color: #fff; }}
    main {{ max-width: 860px; margin: 0 auto; padding: 40px 24px; }}
    .module-section {{ margin-bottom: 48px; }}
    h1 {{ font-size: 24px; font-weight: 600; margin-bottom: 4px; }}
    h2 {{ font-size: 18px; font-weight: 600; margin: 28px 0 12px; }}
    h3 {{ font-size: 15px; font-weight: 600; margin: 0 0 6px; }}
    code {{ font-family: 'SF Mono', Consolas, monospace; font-size: 13px; background: #ede9fe; color: #4c1d95; padding: 1px 5px; border-radius: 4px; }}
    .file-path {{ font-size: 12px; color: #888; margin-bottom: 12px; }}
    .doc {{ color: #374151; margin: 10px 0 16px; white-space: pre-wrap; }}
    .fn-card {{ background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px 20px; margin-bottom: 14px; }}
    .sig {{ font-family: 'SF Mono', Consolas, monospace; font-size: 13px; background: #f3f4f6; padding: 10px 14px; border-radius: 6px; margin-bottom: 10px; overflow-x: auto; }}
    .class-section {{ background: #faf5ff; border: 1px solid #ddd6fe; border-radius: 10px; padding: 20px 24px; margin-bottom: 24px; }}
    hr {{ border: none; border-top: 1px solid #e5e7eb; margin: 40px 0; }}
    footer {{ text-align: center; font-size: 12px; color: #aaa; padding: 24px; }}
  </style>
</head>
<body>
  <nav>
    <h1>{project_name}</h1>
    <ul>{nav_items}</ul>
  </nav>
  <main>
    {module_sections}
  </main>
  <footer>Generated by DocGen · IBM Bob Hackathon 2026</footer>
</body>
</html>"""

    path = os.path.join(output_dir, f"{project_name.lower().replace(' ', '_')}_docs.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return path


# ─── PDF ─────────────────────────────────────────────────────────────────────

def export_pdf(docs: Dict[str, Any], output_dir: str, project_name: str) -> str:
    """
    Export docs as PDF.
    Uses weasyprint if available, falls back to printing instructions.
    """
    html_path = export_html(docs, output_dir, project_name)
    pdf_path = os.path.join(output_dir, f"{project_name.lower().replace(' ', '_')}_docs.pdf")

    try:
        from weasyprint import HTML
        HTML(filename=html_path).write_pdf(pdf_path)
        return pdf_path
    except ImportError:
        note_path = os.path.join(output_dir, "pdf_instructions.txt")
        with open(note_path, "w") as f:
            f.write(
                f"To generate PDF, install weasyprint:\n\n"
                f"  pip install weasyprint\n\n"
                f"Then run:\n\n"
                f"  python -c \"from weasyprint import HTML; HTML('{html_path}').write_pdf('{pdf_path}')\"\n\n"
                f"Or open {os.path.basename(html_path)} in Chrome and use File > Print > Save as PDF.\n"
            )
        return note_path
